### ISSUE TITLE
Update date format from YY to YYYY

### ISSUE THREAD

**Issue by hasan-sf** [Ayn-AI/eyn-api-doc#13]
# ToDo
- Update the sample output in [here](https://ayn-ai.github.io/eyn-api-doc/#document-checks) following the latest from this [README](https://github.com/Ayn-AI/MRZ-Recogniser/blob/master/README.md)

# What's the change?
- dates from YY format to YYYY

**Comment by robin-smileid** [comment]
resolved in 95e0c4617687d93955c90601739639940c0eaa1d
