### ISSUE TITLE
Adding the unusual API response for the French ID's expiry date

### ISSUE THREAD

**Issue by hasan-sf** [Ayn-AI/eyn-api-doc#14]
# Context
- MRZ of a French ID doesn't contain expiry date

# ToDo
- For such French ID, API will respond with `"SEE-BACK-OF-ID"` as the expiry date and therefore please mention that exception in the API doc.

**Comment by robin-smileid** [comment]
resolved in be9c5925a97f7442709ecaaf580cdb1dda5f493d

**Comment by hasan-sf** [comment]
@robin-ankele, Instead of saying `French documents`, would you please update it to `French national ID`? This is because French documents might mean French passport which is fine.

**Comment by robin-smileid** [comment]
> @robin-ankele, Instead of saying `French documents`, would you please update it to `French national ID`? This is because French documents might mean French passport which is fine.

Done.
