### ISSUE TITLE
[Breaking Change] new format for age

### ISSUE THREAD

**Issue by hasan-sf** [Ayn-AI/eyn-api-doc#15]
# ToDo

Instead of returning `age` as following
```
"age": {
    "days": 11358,
    "seconds": 85250,
    "total_seconds": 981416450.424303
```
we return the following 
```
...
    "age": {
        "days": 19,
        "months": 1,
        "years": 31
    },
....
```
- For reference, see update details in [this README](https://github.com/Ayn-AI/MRZ-Recogniser/blob/master/README.md) 

# Warning ⚠️ 
- This is a breaking change. Since nobody is using the API, hopefully it's not a big deal

**Comment by robin-smileid** [comment]
@ratuliut resolved in ed2b213e328096f514641fef065a03f1131d3280
