### ISSUE TITLE
Updating Readme

### ISSUE THREAD

**Issue by hasan-sf** [Ayn-AI/eyn-api-doc#2]
# ToDo
- [x] Create a QuickStart Section that directly takes the user to the Demo Example
- [x] Number https://ayn-ai.github.io/eyn-api-doc/#demos so that it looks like step-by-step instruction

# Ideal Demo 
- git clone repo https://github.com/Ayn-AI/eyn-api-demo
- cd to repo
- virtualenv venv
- pip install -r requirements.txt
- python demo.py
- And you shall see demo response like this
- Ask EYN for your prod credentials and change here and there to access your production data

**Comment by robin-smileid** [comment]
@ratuliut  resolved in d2d5f8c

**Comment by robin-smileid** [comment]
@ratuliut closing this issue since it is resolve in d2d5f8c
